### ISSUE TITLE
update client origin to medithanks.co

### ISSUE THREAD

**Issue by davidholyko** [PB-J/frontline-backend#3]
https://github.com/PB-J/frontline-backend/blob/main/server.js#L42

Heroku config vars for CLIENT_ORIGIN should be medithanks.co

**Comment by simonchen92** [comment]
![image](https://user-images.githubusercontent.com/46136260/106362222-ac28e880-62ef-11eb-850c-301a6f176b28.png)

**Comment by simonchen92** [comment]
I have updated client origin in heroku per your issue above
